# Generated by Django 4.1.5 on 2023-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileup',
            name='file_upper',
            field=models.FileField(max_length='3000', upload_to='images/'),
        ),
    ]
