# Generated by Django 4.1.5 on 2023-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_alter_fileup_file_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileup',
            name='file_upper',
            field=models.FileField(upload_to='images/'),
        ),
    ]
